name: Publish CUPS Docker Image to Docker Hub

# Controls when the action will be run
on:
  # triggers on push or pull request events on main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 3 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        variant: [ bookworm, bookworm-slim, bullseye, bullseye-slim ]
    # sequence of tasks in the build process
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/cups:${{ matrix.variant }}
            ${{ (matrix.variant == 'bookworm-slim' && format('{0}/cups:latest', secrets.DOCKER_USER)) || '' }}
          build-args: |
            BASE_IMAGE=debian:${{ matrix.variant }}
